### ISSUE TITLE
Feature: support goerli test network 

### ISSUE THREAD

**Issue by sambacha** [interep-project/reputation-service#103]
Goerli will be the only surviving test network after the merge,  with kovan and rinkeby slated to see EOL by EOY.

What would it take to get a deployment on Goerli? 

Thanks!

**Comment by cedoor** [comment]
This is a good point thanks! Moved this issue in the next sprint board.

We need to deploy the Interep contracts on Goerli and deploy another web app: `goerli.interep.link`. We could keep both or replace Kovan with Georli in the near future.

**Comment by sambacha** [comment]
> This is a good point thanks! Moved this issue in the next sprint board.
> 
> 
> 
> We need to deploy the Interep contracts on Goerli and deploy another web app: `goerli.interep.link`. We could keep both or replace Kovan with Georli in the near future.

Thank you, this is a blocker for us, in the meantime let me know how i can help

**Comment by cedoor** [comment]
@sambacha  

Interep Goerli is now active on https://goerli.interep.link. New contract address here: https://github.com/interep-project/contracts.
